<?php
/**
 * CardStateResponsePlzftCard
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Plasticard\PLZFT
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Order API ADN/Leifos
 *
 * ### This API receives and processes orders for ADN/Leifos DEVELOPMENT ENVIROMENT
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developer@plasticard.de
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plasticard\PLZFT\Model;

use \ArrayAccess;
use \Plasticard\PLZFT\ObjectSerializer;

/**
 * CardStateResponsePlzftCard Class Doc Comment
 *
 * @category Class
 * @package  Plasticard\PLZFT
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CardStateResponsePlzftCard implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CardStateResponse_plzft_Card';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'plzft_id' => 'int',
        'plzft_certificate_id' => 'string',
        'plzft_production_state' => 'int',
        'plzft_uid' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'plzft_id' => null,
        'plzft_certificate_id' => null,
        'plzft_production_state' => null,
        'plzft_uid' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'plzft_id' => false,
		'plzft_certificate_id' => false,
		'plzft_production_state' => false,
		'plzft_uid' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'plzft_id' => 'plzft:Id',
        'plzft_certificate_id' => 'plzft:CertificateId',
        'plzft_production_state' => 'plzft:ProductionState',
        'plzft_uid' => 'plzft:UID'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'plzft_id' => 'setPlzftId',
        'plzft_certificate_id' => 'setPlzftCertificateId',
        'plzft_production_state' => 'setPlzftProductionState',
        'plzft_uid' => 'setPlzftUid'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'plzft_id' => 'getPlzftId',
        'plzft_certificate_id' => 'getPlzftCertificateId',
        'plzft_production_state' => 'getPlzftProductionState',
        'plzft_uid' => 'getPlzftUid'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('plzft_id', $data ?? [], null);
        $this->setIfExists('plzft_certificate_id', $data ?? [], null);
        $this->setIfExists('plzft_production_state', $data ?? [], null);
        $this->setIfExists('plzft_uid', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets plzft_id
     *
     * @return int|null
     */
    public function getPlzftId()
    {
        return $this->container['plzft_id'];
    }

    /**
     * Sets plzft_id
     *
     * @param int|null $plzft_id plzft_id
     *
     * @return self
     */
    public function setPlzftId($plzft_id)
    {
        if (is_null($plzft_id)) {
            throw new \InvalidArgumentException('non-nullable plzft_id cannot be null');
        }
        $this->container['plzft_id'] = $plzft_id;

        return $this;
    }

    /**
     * Gets plzft_certificate_id
     *
     * @return string|null
     */
    public function getPlzftCertificateId()
    {
        return $this->container['plzft_certificate_id'];
    }

    /**
     * Sets plzft_certificate_id
     *
     * @param string|null $plzft_certificate_id plzft_certificate_id
     *
     * @return self
     */
    public function setPlzftCertificateId($plzft_certificate_id)
    {
        if (is_null($plzft_certificate_id)) {
            throw new \InvalidArgumentException('non-nullable plzft_certificate_id cannot be null');
        }
        $this->container['plzft_certificate_id'] = $plzft_certificate_id;

        return $this;
    }

    /**
     * Gets plzft_production_state
     *
     * @return int|null
     */
    public function getPlzftProductionState()
    {
        return $this->container['plzft_production_state'];
    }

    /**
     * Sets plzft_production_state
     *
     * @param int|null $plzft_production_state plzft_production_state
     *
     * @return self
     */
    public function setPlzftProductionState($plzft_production_state)
    {
        if (is_null($plzft_production_state)) {
            throw new \InvalidArgumentException('non-nullable plzft_production_state cannot be null');
        }
        $this->container['plzft_production_state'] = $plzft_production_state;

        return $this;
    }

    /**
     * Gets plzft_uid
     *
     * @return string|null
     */
    public function getPlzftUid()
    {
        return $this->container['plzft_uid'];
    }

    /**
     * Sets plzft_uid
     *
     * @param string|null $plzft_uid plzft_uid
     *
     * @return self
     */
    public function setPlzftUid($plzft_uid)
    {
        if (is_null($plzft_uid)) {
            throw new \InvalidArgumentException('non-nullable plzft_uid cannot be null');
        }
        $this->container['plzft_uid'] = $plzft_uid;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


