<?php
/**
 * OrderPlzftCertificatePlzftReturnAddress
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Plasticard\PLZFT
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ADN/leifos - OpenAPI 3.0
 *
 * Definition of the REST API for ADN/leifos
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: developer@plasticard.de
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plasticard\PLZFT\Model;

use \ArrayAccess;
use \Plasticard\PLZFT\ObjectSerializer;

/**
 * OrderPlzftCertificatePlzftReturnAddress Class Doc Comment
 *
 * @category Class
 * @package  Plasticard\PLZFT
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OrderPlzftCertificatePlzftReturnAddress implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Order_plzft_Certificate_plzft_ReturnAddress';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'plzft_address_name' => 'string',
        'plzft_address_street' => 'string',
        'plzft_address_postal_code' => 'string',
        'plzft_address_city' => 'string',
        'plzft_address_country' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'plzft_address_name' => null,
        'plzft_address_street' => null,
        'plzft_address_postal_code' => null,
        'plzft_address_city' => null,
        'plzft_address_country' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'plzft_address_name' => false,
		'plzft_address_street' => false,
		'plzft_address_postal_code' => false,
		'plzft_address_city' => false,
		'plzft_address_country' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'plzft_address_name' => 'plzft:AddressName',
        'plzft_address_street' => 'plzft:AddressStreet',
        'plzft_address_postal_code' => 'plzft:AddressPostalCode',
        'plzft_address_city' => 'plzft:AddressCity',
        'plzft_address_country' => 'plzft:AddressCountry'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'plzft_address_name' => 'setPlzftAddressName',
        'plzft_address_street' => 'setPlzftAddressStreet',
        'plzft_address_postal_code' => 'setPlzftAddressPostalCode',
        'plzft_address_city' => 'setPlzftAddressCity',
        'plzft_address_country' => 'setPlzftAddressCountry'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'plzft_address_name' => 'getPlzftAddressName',
        'plzft_address_street' => 'getPlzftAddressStreet',
        'plzft_address_postal_code' => 'getPlzftAddressPostalCode',
        'plzft_address_city' => 'getPlzftAddressCity',
        'plzft_address_country' => 'getPlzftAddressCountry'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('plzft_address_name', $data ?? [], null);
        $this->setIfExists('plzft_address_street', $data ?? [], null);
        $this->setIfExists('plzft_address_postal_code', $data ?? [], null);
        $this->setIfExists('plzft_address_city', $data ?? [], null);
        $this->setIfExists('plzft_address_country', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets plzft_address_name
     *
     * @return string|null
     */
    public function getPlzftAddressName()
    {
        return $this->container['plzft_address_name'];
    }

    /**
     * Sets plzft_address_name
     *
     * @param string|null $plzft_address_name plzft_address_name
     *
     * @return self
     */
    public function setPlzftAddressName($plzft_address_name)
    {
        if (is_null($plzft_address_name)) {
            throw new \InvalidArgumentException('non-nullable plzft_address_name cannot be null');
        }
        $this->container['plzft_address_name'] = $plzft_address_name;

        return $this;
    }

    /**
     * Gets plzft_address_street
     *
     * @return string|null
     */
    public function getPlzftAddressStreet()
    {
        return $this->container['plzft_address_street'];
    }

    /**
     * Sets plzft_address_street
     *
     * @param string|null $plzft_address_street plzft_address_street
     *
     * @return self
     */
    public function setPlzftAddressStreet($plzft_address_street)
    {
        if (is_null($plzft_address_street)) {
            throw new \InvalidArgumentException('non-nullable plzft_address_street cannot be null');
        }
        $this->container['plzft_address_street'] = $plzft_address_street;

        return $this;
    }

    /**
     * Gets plzft_address_postal_code
     *
     * @return string|null
     */
    public function getPlzftAddressPostalCode()
    {
        return $this->container['plzft_address_postal_code'];
    }

    /**
     * Sets plzft_address_postal_code
     *
     * @param string|null $plzft_address_postal_code plzft_address_postal_code
     *
     * @return self
     */
    public function setPlzftAddressPostalCode($plzft_address_postal_code)
    {
        if (is_null($plzft_address_postal_code)) {
            throw new \InvalidArgumentException('non-nullable plzft_address_postal_code cannot be null');
        }
        $this->container['plzft_address_postal_code'] = $plzft_address_postal_code;

        return $this;
    }

    /**
     * Gets plzft_address_city
     *
     * @return string|null
     */
    public function getPlzftAddressCity()
    {
        return $this->container['plzft_address_city'];
    }

    /**
     * Sets plzft_address_city
     *
     * @param string|null $plzft_address_city plzft_address_city
     *
     * @return self
     */
    public function setPlzftAddressCity($plzft_address_city)
    {
        if (is_null($plzft_address_city)) {
            throw new \InvalidArgumentException('non-nullable plzft_address_city cannot be null');
        }
        $this->container['plzft_address_city'] = $plzft_address_city;

        return $this;
    }

    /**
     * Gets plzft_address_country
     *
     * @return string|null
     */
    public function getPlzftAddressCountry()
    {
        return $this->container['plzft_address_country'];
    }

    /**
     * Sets plzft_address_country
     *
     * @param string|null $plzft_address_country plzft_address_country
     *
     * @return self
     */
    public function setPlzftAddressCountry($plzft_address_country)
    {
        if (is_null($plzft_address_country)) {
            throw new \InvalidArgumentException('non-nullable plzft_address_country cannot be null');
        }
        $this->container['plzft_address_country'] = $plzft_address_country;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


